import Link from "next/link";import{SellerActivation}from"@/components/admin/seller-activation";
import { PageContainer } from "@/components/shared/page-container";
import { PageHeader } from "@/components/shared/page-header";
import { StatusChip } from "@/components/shared/status-chip";
import { ADMIN_SELLER_STATUS_PRESENTATION, ADMIN_SELLER_SYSTEM_STATUSES, type AdminSellerSystemStatus } from "@/lib/admin/seller-format";
import { resolveAdminSellerFromSession, resolveAdminSellersFromSession } from "@/lib/admin/sellers-server";
const one=(v:string|string[]|undefined)=>typeof v==="string"?v:undefined;
export default async function AdminSellersPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const p=await searchParams;const raw=one(p.status);const status=ADMIN_SELLER_SYSTEM_STATUSES.includes(raw as AdminSellerSystemStatus)?raw as AdminSellerSystemStatus:undefined;const q=one(p.q)?.trim()||undefined;const id=Number(one(p.seller));const list=await resolveAdminSellersFromSession({q,status,limit:30,offset:0});const detail=Number.isInteger(id)&&id>0?await resolveAdminSellerFromSession(id):null;return <PageContainer size="wide" className="py-8 sm:py-10"><PageHeader caption="YÖNETİM" title="Mağazalar" description="Seller’ların kurulum, aktivasyon ve çalışma durumlarını izleyin."/><div className="mt-8 grid overflow-hidden rounded-sheet border border-boundary/70 bg-raised shadow-surface lg:grid-cols-[360px_minmax(0,1fr)]"><aside className="border-b border-divider lg:border-b-0 lg:border-r"><div className="border-b border-divider p-4"><form className="flex gap-2"><input name="q" defaultValue={q} placeholder="Mağaza veya yetkili ara" className="min-w-0 flex-1 rounded-control border border-boundary bg-control px-3 py-2 type-row-secondary text-foreground"/><button className="rounded-control bg-primary px-3 type-row-secondary font-semibold text-primary-foreground">Ara</button></form><div className="mt-3 flex flex-wrap gap-2">{[undefined,...ADMIN_SELLER_SYSTEM_STATUSES].map(s=>{const href=new URLSearchParams();if(q)href.set("q",q);if(s)href.set("status",s);return <Link key={s??"all"} href={`/admin/sellers${href.size?`?${href}`:""}` as import("next").Route} className={`rounded-pill px-2 py-1 type-meta ${status===s?"bg-primary/15 text-primary":"text-muted-foreground hover:bg-elevated"}`}>{s?ADMIN_SELLER_STATUS_PRESENTATION[s].label:"Tümü"}</Link>})}</div></div>{list.state==="ready"?<ul>{list.page.sellers.map(x=>{const v=ADMIN_SELLER_STATUS_PRESENTATION[x.systemStatus];return <li key={x.id} className="border-b border-divider last:border-0"><Link href={`/admin/sellers?seller=${x.id}${status?`&status=${status}`:""}${q?`&q=${encodeURIComponent(q)}`:""}` as import("next").Route} className="block px-4 py-4 hover:bg-elevated"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate type-row-primary text-foreground">{x.storeName}</p><p className="mt-0.5 truncate type-row-secondary text-muted">{x.name}</p></div><StatusChip tone={v.tone}>{v.label}</StatusChip></div></Link></li>})}</ul>:<p className="p-5 type-row-secondary text-muted">Mağaza listesi şu anda yüklenemedi.</p>}</aside><section className="min-h-[420px] p-5 sm:p-6">{detail?.state==="ready"?<SellerDetail seller={detail.seller}/>:detail?.state==="not_found"?<p className="type-body text-muted">Bu mağaza artık görüntülenemiyor.</p>:detail?<p className="type-body text-muted">Mağaza detayı şu anda yüklenemedi.</p>:<p className="type-body text-muted">Detayları görmek için listeden bir mağaza seçin.</p>}</section></div></PageContainer>}
function SellerDetail({seller}:{seller:import("@/lib/admin/sellers-api").AdminSeller}){const v=ADMIN_SELLER_STATUS_PRESENTATION[seller.systemStatus];return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="type-meta text-muted-foreground">MAĞAZA DETAYI</p><h2 className="mt-2 type-section text-foreground">{seller.storeName}</h2><p className="mt-1 type-row-secondary text-muted">{seller.name}</p></div><StatusChip tone={v.tone}>{v.label}</StatusChip></div><dl className="grid gap-4 border-t border-divider pt-5 sm:grid-cols-2"><Item label="Kurulum" value={seller.onboardingCompleted?"Tamamlandı":seller.onboardingStatus??"Devam ediyor"}/><Item label="AI durumu" value={seller.aiEnabled?"Aktif":"Aktif değil"}/><Item label="Oluşturulma" value={new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium"}).format(new Date(seller.createdAt))}/><Item label="Son güncelleme" value={new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium"}).format(new Date(seller.updatedAt))}/></dl><div className="flex flex-wrap items-center gap-4">{seller.storeLink?<a href={seller.storeLink} target="_blank" rel="noreferrer" className="type-row-secondary text-primary hover:underline">Mağaza bağlantısını aç</a>:null}<SellerActivation seller={seller}/></div></div>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="type-meta text-muted-foreground">{label}</dt><dd className="mt-1 type-row-primary text-foreground">{value}</dd></div>}
